# Permalinks
#
permalink:           pretty

# Setup
title:               mor
tagline:             'A door.'
description:         'This site shows works and projects done by and with Alexander Morosow.'
url:                 http://mor.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alexander Morosow
  url:               http://mor.github.io
  email:             alexander.morosow@gmail.com

# Custom vars
version:             0.0.1
